version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - privateNetwork
    container_name: Client

  hsm:
    build:
      context: ./hsm_server
      dockerfile: Dockerfile.hsm
    ports:
      - "5000:5000"
    expose:
      - 5000
    networks:
      - privateNetwork
    container_name: Server

networks:
  privateNetwork: